"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const api_1 = require("../enums/api");
const user_1 = require("../controllers/user");
const verifyToken_1 = require("../utils/verifyToken");
const upload_1 = require("../utils/upload");
const validateEmail_1 = require("../utils/validateEmail");
const getCode_1 = require("../utils/getCode");
const decCode_1 = require("../utils/decCode");
const getId_1 = require("../utils/getId");
const router = express_1.default.Router();
router.get(api_1.api.findUser, verifyToken_1.verifyToken, user_1.getUser);
router.put(api_1.api.addTolist, verifyToken_1.verifyToken, user_1.addToList);
router.put(api_1.api.removeFromList, verifyToken_1.verifyToken, user_1.removeFromList);
router.put(api_1.api.likes, verifyToken_1.verifyToken, user_1.addToLikes);
router.put(api_1.api.dislike, verifyToken_1.verifyToken, user_1.removeFromLikes);
router.put(api_1.api.incUnread, verifyToken_1.verifyToken, user_1.unreadInc);
router.put(api_1.api.emptyUnread, verifyToken_1.verifyToken, user_1.unreadEmpty);
router.put(api_1.api.editPassword, verifyToken_1.verifyToken, user_1.editPassword);
router.post(api_1.api.editProfile, verifyToken_1.verifyToken, upload_1.uploadSingle, user_1.editProfile);
router.post(api_1.api.sendEmail, validateEmail_1.validateEmail, getCode_1.getCode, user_1.sendEmail);
router.post(api_1.api.validateCode, decCode_1.decCode, user_1.validateCode, getId_1.getId);
router.put(api_1.api.forgotPassword, verifyToken_1.verifyToken, user_1.forgotPassword);
exports.default = router;
