
"use client"

import dynamic from 'next/dynamic'
import "./App.scss"
// import { Metadata } from 'next';
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const Home = dynamic(()=> import('../pages/home/Home'),{
  loading:()=><p>Loading..</p>,
  ssr:false
}

) 





export default function App() {

  return (
 
    // <AuthContextProvider >
  
   
      <Home/>
      
    /* </AuthContextProvider> */
  );
}
